steps:
  #Execute SonarCloud Scan
  - name: maven:3-jdk-17
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=gcpsourcecodorg','-Dsonar.projectKey=gcpsourcecodprojectkey','-Dsonar.login=${_SONAR_TOKEN}']
